# Netlify configuration file

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to set
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co https://api.ipify.org https://www.cpagrip.com https://motifiles.com https://images.unsplash.com; img-src 'self' data: https://*.googleusercontent.com https://images.unsplash.com https://*.rw https://*.googleusercontent.com https://play-lh.googleusercontent.com; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:;"

# Environment variables
[build.environment]
  NODE_VERSION = "18"